data:
  ais_dir: "/PATH_TO_RAINDROP_SIMULATION/out/ais/"
  spl_dir: "/PATH_TO_RAINDROP_SIMULATION/out/pickles/"
  example_nc_path: "/PATH_TO_RAINDROP_SIMULATION/out/nc/ANY_NC_FILE.nc"
  bathy_csv: "/PATH_TO_RAINDROP_SIMULATION//bathymetry/BATHYMETRY_DATA.csv"
  coastline_shp: "/PATH_TO_RAINDROP_SIMULATION/coastline/COASTLINE_DATA.shp"
  cache_dir: "cache"
  crop_size: 1000     # Set to the same resolution as the SPL/bathymetry resolution. Using a lower resolution will crop the ROI in the center leading to a crop_size x crop_size square region of interest. 
  use_63hz: false     # Switch to decide the SPL files to train on
  use_pascal: false   # Set training on the Pascal linear scale. Setting to true may hinder performance
  num_rays: 360       # Number of rays to sample for each ship. 
  ray_points: 256     # Number of points to sample along each ray.


model:
  bathy_latent: 128   # Latent dimension for the bathymetry encoder
  ais_latent: 64      # Latent dimension for the AIS encoder


training:
  batch_size: 16      
  num_epochs: 200     # Maximum number of epochs to train for.
  lr: 0.0001          # Learning rate for the Adam optimizer.
  seed: 42            # Set a random seed for reproducibility. Set to None to disable.
  train_split: 0.8    # Proportion of the dataset to use for training.
  val_split:   0.1    # Proportion of the dataset to use for validation.
  output_dir: "results/figures"
  checkpoint_dir: "checkpoints"
  use_cuda: true      # Toggle CUDA usage for training (recommended).


mlflow:
  enabled: true       # Toggle MLflow tracking for experiments. 
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "RAINDROP Surrogate Model Training"


evaluation:
  batch_size: 32      # Can differ from training batch size
  checkpoint_path: "checkpoints/best_model.pth"
  output_dir: "results/evaluation"
  num_plots: 10       # Number of samples to plot radial comparisons for